### ISSUE TITLE
Helios does not build on Haiku

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Helios#1]
Downloaded the Helios-master and ran make. Many errors in the source files. I would like to test this app on Haiku due to its more advanced development (compared to other burning apps) at the time of the demise of BeOS.

**Comment by waddlesplash** [comment]
Oh, looks like diver already fixed this in fdf4686a2ecd79287cdb73c58e569863b4c9dbb4.

**Comment by Vidrep** [comment]
Thanks guys!
