### ISSUE TITLE
Copy Audio CD strange problem

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Helios#3]
This is really strange. I used the copy audio CD function. Helios burned a disk. When I reloaded the disk the title of the newly burned disk was "Lesch, Prof. Harold - Sind wir allein im Universum", which is definately not what I copied. Zeta was a German distribution, correct? It seems some cruft was left in the source files. It was an amusing test.

**Comment by pulkomandy** [comment]
Hi,
I think this is a limitation of the CDDB system. Haiku will scan the trac durations from audio CDs and compute a checksum from that. It will then ask the online CDDB database to find a matching CD. The CDDB is known to have collisions, and if Helios changes the track durations, even very slightly, the resulting CD will have a different signature and may match something else in the CDDB database.

In this case your CD signature matches http://www.wissenschaft-shop.de/themenwelten/astronomie-raumfahrt/prof-harald-lesch-sind-wir-allein-im-universum.html. Completely unrelated to Zeta being German.
